# This is a basic workflow to help you get started with Actions

name: build_ISO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          sudo apt update && sudo apt install -y syslinux-utils xorriso
          wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso
          sudo bash create_ISO.bash

      # Release custom ISO
      - uses: ncipollo/release-action@v1
        with:
          commit: "main"
          name: "Download ISO"
          tag: "12.5"
          artifacts: "proxmox_custom.iso"
